/' ========================================================================== *
 * Copyright (C) 2023 HCL America Inc.                                        *
 * Apache-2.0 license   https://www.apache.org/licenses/LICENSE-2.0           *
 * ========================================================================== '/
@startuml SDK Components
header // Domino REST API NodeJS/TypeScript SDK //

cloud {
  (Domino REST API) as drapi
}

package Authentication {
  [DominoAccess] as da
  () "access parameters" as ap
  () "access token" as at
}

package Server {
  [DominoServer] as ds
  [DominoConnector] as dc
  () "server parameters" as sp
  () "server APIs" as sa
  () "API details" as ad
}

package Session {
  [DominoUserSession] as dus
  [DominoBasisSession] as dbs
  [DominoSetupSession] as dss
  () "generic request methods" as grm
  () "document operation methods" as dom
  () "list view operation methods" as dvom
  () "scope operation methods" as som
}

() "node-fetch" as nf

drapi <--> nf

da ..> ap
at - da
nf <.. da

ds ..> sp
ds -- sa
dc <-- ds: creates
dc -- ad
nf ..> ds
nf ..> dc

dus -- grm
dbs -- dom
dbs -- dvom
dss -- dvom
dss -- som
da <.. dus
dc <.. dus
da <.. dbs
ds <.. dbs
da <.. dss
ds <.. dss

footer //Domino REST SDK //
@enduml