@startuml SDK Components
header // Domino REST API NodeJS/TypeScript SDK //

package "Authentication" {
() "DominoRestAccess" as dra
() "RestCredentials" as rc
[DominoAccess] as dac
}


() "DominoRestSession" as drs
[DominoServer] as server
[DominoSession] as dsc
[DominoRestConnector] as drc

package "Scope" {
() "DominoScope" as ds
() "QueryParams" as qp
() "DominoList" as dl
() "DominoDocumentMode" as ddm
[ScopeInstance] as sic
[DominoListInstance] as dli
[DominoDocument] as doc
}

cloud {
    [KEEP]
    () "Node Fetch" as nf
}

[KEEP] <.. nf
[KEEP] <.. nf
server <.. nf
nf <.. drc
nf <.. dra
drc <..> dsc : abstract fetch
dra -> dac
dac <-- rc
dac . drc
dac .> dsc: initialize
dsc <- drs
ds -> sic
dsc --> sic : acess to scope
drc <..> sic
dli <..> drc
doc <..> drc
sic --> dli
dl --> dli
qp --> dli
sic --> ddm
dli .. ddm
ddm .. doc
sic --> doc
footer //Domino REST SDK //
@enduml